#!/usr/bin/env ruby

$:.unshift File.expand_path("../../lib", __FILE__)
require "envandle"
require "tempfile"

gem_source = "https://rubygems.org"
bundle_bin = "bundle"

args = []
argv = ARGV.dup
while arg = argv.shift
  if arg.start_with?("--gemfile")
    abort "--gemfile option not allowed."
  end
  case arg
  when "--envandle-source"
    gem_source = argv.shift
  when "--envandle-bundle-bin"
    bundle_bin = argv.shift
  when "-h", "--help"
    print <<-EOS
install-envandle [OPTIONS]

Installs Envandle using Bundler.

Options:
  --envandle-source      gem source (default: https://rubygems.org)
  --envandle-bundle-bin  command path (default: bundle)

Additionally, you can specify all of the bundle-install's options.
EOS
    exit
  else
    args << arg
  end
end

abort "Invalid option: --envandle-source" unless gem_source
abort "Invalid option: --bundle-bin" unless bundle_bin

gemfile = Tempfile.new("install_envandle-Gemfile-", Dir.pwd)
gemfile << <<-EOS
source #{gem_source.inspect}
gem "envandle", "#{Envandle::VERSION}"
EOS
gemfile.close
code = system(bundle_bin, "install", "--gemfile", gemfile.path, *args) ? 0 : 1
File.delete "#{gemfile.path}.lock"
exit code
